import { writeFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const previewRoot = path.join(root, 'outputs', 'deforum-merged-previews');

const initImage = 'D:/Users/User/Sonar/VIdeoArt/outputs/deforum-merged-previews/WOMANS/WOMANS.png';

const settings = {
  W: 768,
  H: 432,
  show_info_on_ui: true,
  tiling: false,
  restore_faces: false,
  seed_resize_from_w: 0,
  seed_resize_from_h: 0,
  seed: 19082601,
  sampler: 'Euler a',
  steps: 24,
  batch_name: 'WOMANS_DEFORUM_MORPH_V1_30SEC',
  seed_behavior: 'fixed',
  seed_iter_N: 1,
  use_init: true,
  strength: 0.6,
  strength_0_no_init: false,
  init_image: initImage,
  use_mask: false,
  use_alpha_as_mask: false,
  invert_mask: false,
  mask_contrast_adjust: 1,
  mask_brightness_adjust: 1,
  overlay_mask: true,
  mask_overlay_blur: 4,
  fill: 1,
  full_res_mask: true,
  full_res_mask_padding: 24,
  reroll_blank_frames: {
    label: 'Reroll blank frames',
    type: 'radio',
    choices: ['reroll', 'interrupt', 'ignore'],
    value: 'ignore',
    info: ''
  },
  reroll_patience: 10,
  motion_preview_mode: false,
  noise_type: {
    label: 'Noise type',
    type: 'radio',
    choices: ['Perlin', 'Simplex', 'Uniform', 'Normal', 'Brownian'],
    value: 'Perlin',
    info: ''
  },
  prompts: {
    '0': 'the same woman from the init image, serene centered portrait, facing the viewer, soft cinematic light, high detail',
    '90': 'the same woman turning her head slightly to the side, gentle expression, soft studio light, high detail',
    '180': 'the same woman in a dreamlike garden, golden hour light, flowing hair, cinematic, high detail',
    '270': 'the same woman standing by a moonlit ocean, night sky, stars, cinematic, high detail',
    '359': 'the same woman returning to a calm centered portrait, eyes softly closed, peaceful, cinematic, high detail'
  },
  positive_prompts: '',
  negative_prompts: 'text, watermark, signature, logo, extra limbs, extra head, missing limbs, malformed anatomy, deformed face, two people, multiple faces, duplicate, double exposure, ghosting, camera, lens, zoom, crop, pan, camera movement, warm oversaturation, blurry, low quality',
  animation_mode: '2D',
  max_frames: 360,
  border: 'replicate',
  angle: '0: (0)',
  zoom: '0: (1.0)',
  translation_x: '0: (0)',
  translation_y: '0: (0)',
  translation_z: '0: (0)',
  transform_center_x: '0: (0.5)',
  transform_center_y: '0: (0.5)',
  rotation_3d_x: '0: (0)',
  rotation_3d_y: '0: (0)',
  rotation_3d_z: '0: (0)',
  enable_perspective_flip: false,
  perspective_flip_theta: '0: (0)',
  perspective_flip_phi: '0: (0)',
  perspective_flip_gamma: '0: (0)',
  perspective_flip_fv: '0: (53)',
  noise_schedule: '0: (0)',
  strength_schedule: '0: (0.6)',
  contrast_schedule: '0: (1.0)',
  cfg_scale_schedule: '0: (5.5)',
  enable_steps_scheduling: false,
  steps_schedule: '0: (1)',
  fov_schedule: '0: (70)',
  aspect_ratio_schedule: '0: (1)',
  aspect_ratio_use_old_formula: false,
  near_schedule: '0: (200)',
  far_schedule: '0: (10000)',
  seed_schedule: '0: (s)',
  pix2pix_img_cfg_scale_schedule: '0: (1.5)',
  enable_subseed_scheduling: false,
  subseed_schedule: '0: (1)',
  subseed_strength_schedule: '0: (0)',
  enable_sampler_scheduling: false,
  sampler_schedule: '0: ("Euler a")',
  use_noise_mask: false,
  mask_schedule: '0: ("{video_mask}")',
  noise_mask_schedule: '0: ("{video_mask}")',
  enable_checkpoint_scheduling: false,
  checkpoint_schedule: '0: ("model1.ckpt"), 100: ("model2.safetensors")',
  enable_clipskip_scheduling: false,
  clipskip_schedule: '0: (2)',
  enable_noise_multiplier_scheduling: false,
  noise_multiplier_schedule: '0: (1.0)',
  resume_from_timestring: true,
  resume_timestring: '20260819153319',
  enable_ddim_eta_scheduling: false,
  ddim_eta_schedule: '0: (0)',
  enable_ancestral_eta_scheduling: false,
  ancestral_eta_schedule: '0: (1)',
  amount_schedule: '0: (0.1)',
  kernel_schedule: '0: (5)',
  sigma_schedule: '0: (1)',
  threshold_schedule: '0: (0)',
  color_coherence: 'Image',
  color_coherence_image_path: initImage,
  color_coherence_video_every_N_frames: 1,
  color_force_grayscale: false,
  legacy_colormatch: true,
  diffusion_cadence: 1,
  optical_flow_cadence: 'None',
  cadence_flow_factor_schedule: '0: (1)',
  optical_flow_redo_generation: 'None',
  redo_flow_factor_schedule: '0: (1)',
  diffusion_redo: '0',
  cn_1_weight: '0:(1.0)',
  cn_1_guidance_start: '0:(0)',
  cn_1_guidance_end: '0:(1)',
  cn_2_weight: '0:(1.0)',
  cn_2_guidance_start: '0:(0)',
  cn_2_guidance_end: '0:(1)',
  cn_3_weight: '0:(1.0)',
  cn_3_guidance_start: '0:(0)',
  cn_3_guidance_end: '0:(1)',
  cn_4_weight: '0:(1.0)',
  cn_4_guidance_start: '0:(0)',
  cn_4_guidance_end: '0:(1)',
  cn_5_weight: '0:(1.0)',
  cn_5_guidance_start: '0:(0)',
  cn_5_guidance_end: '0:(1)'
};

const response = await fetch('http://127.0.0.1:7860/deforum_api/batches', {
  method: 'POST',
  headers: { 'content-type': 'application/json' },
  body: JSON.stringify({ deforum_settings: [settings], options_overrides: {} })
});
if (!response.ok) throw new Error(`${response.status} ${await response.text()}`);
const result = await response.json();
writeFileSync(
  path.join(previewRoot, 'WOMANS_DEFORUM_MORPH_V1_30SEC_resume_submit.json'),
  JSON.stringify({ submittedAt: new Date().toISOString(), result, settings }, null, 2)
);
console.log(JSON.stringify(result, null, 2));
