import { writeFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const previewRoot = path.join(root, 'outputs', 'deforum-merged-previews');

const settings = {
  W: 576,
  H: 1024,
  show_info_on_ui: true,
  tiling: false,
  restore_faces: false,
  seed_resize_from_w: 0,
  seed_resize_from_h: 0,
  seed: 13781977,
  sampler: 'Euler',
  steps: 22,
  batch_name: 'CARA_DEFORUM_GETUP_V137',
  seed_behavior: 'fixed',
  seed_iter_N: 1,
  use_init: true,
  strength: 0.6,
  strength_0_no_init: false,
  init_image: 'D:/Users/User/Sonar/VIdeoArt/outputs/deforum-merged-previews/_cara_scene_init_576x1024.png',
  use_mask: true,
  use_alpha_as_mask: false,
  mask_file: 'D:/Users/User/Sonar/VIdeoArt/outputs/deforum-merged-previews/CARA_getup_mask.png',
  invert_mask: false,
  mask_contrast_adjust: 1,
  mask_brightness_adjust: 1,
  overlay_mask: true,
  mask_overlay_blur: 10,
  fill: 1,
  full_res_mask: true,
  full_res_mask_padding: 24,
  reroll_blank_frames: {
    label: 'Reroll blank frames',
    type: 'radio',
    choices: ['reroll', 'interrupt', 'ignore'],
    value: 'ignore',
    info: ''
  },
  reroll_patience: 10,
  motion_preview_mode: false,
  noise_type: {
    label: 'Noise type',
    type: 'radio',
    choices: ['Perlin', 'Simplex', 'Uniform', 'Normal', 'Brownian'],
    value: 'Perlin',
    info: ''
  },
  prompts: {
    '0': 'the same figure from the init image lying down in place, gray-blue CRT pixel art, cyan rim glow, dark teal dot-matrix background, high quality',
    '24': 'the same figure lifting its head and raising its torso, beginning to rise, gray-blue CRT pixel art, cyan rim glow, dark teal dot-matrix background',
    '48': 'the same figure sitting upright, mid rise, gray-blue CRT pixel art, cyan rim glow, dark teal dot-matrix background',
    '72': 'the same figure standing upright, full body, gray-blue CRT pixel art, cyan rim glow, dark teal dot-matrix background'
  },
  positive_prompts: '',
  negative_prompts: 'camera, lens, machine, machinery, device, equipment, robot, vehicle, object, text, watermark, illustration style change, different figure, extra limbs, extra head, missing limbs, malformed anatomy, zoom, crop, pan, camera movement, background movement, warm colors, red, orange, green',
  animation_mode: '2D',
  max_frames: 73,
  border: 'replicate',
  angle: '0: (0)',
  zoom: '0: (1.0)',
  translation_x: '0: (0)',
  translation_y: '0: (0)',
  translation_z: '0: (0)',
  transform_center_x: '0: (0.5)',
  transform_center_y: '0: (0.5)',
  rotation_3d_x: '0: (0)',
  rotation_3d_y: '0: (0)',
  rotation_3d_z: '0: (0)',
  enable_perspective_flip: false,
  perspective_flip_theta: '0: (0)',
  perspective_flip_phi: '0: (0)',
  perspective_flip_gamma: '0: (0)',
  perspective_flip_fv: '0: (53)',
  noise_schedule: '0: (0)',
  strength_schedule: '0: (0.6)',
  contrast_schedule: '0: (1.0)',
  cfg_scale_schedule: '0: (5.5)',
  enable_steps_scheduling: false,
  steps_schedule: '0: (1)',
  fov_schedule: '0: (70)',
  aspect_ratio_schedule: '0: (1)',
  aspect_ratio_use_old_formula: false,
  near_schedule: '0: (200)',
  far_schedule: '0: (10000)',
  seed_schedule: '0: (s)',
  pix2pix_img_cfg_scale_schedule: '0: (1.5)',
  enable_subseed_scheduling: false,
  subseed_schedule: '0: (1)',
  subseed_strength_schedule: '0: (0)',
  enable_sampler_scheduling: false,
  sampler_schedule: '0: ("Euler")',
  use_noise_mask: false,
  mask_schedule: '0: ("{video_mask}")',
  noise_mask_schedule: '0: ("{video_mask}")',
  enable_checkpoint_scheduling: false,
  checkpoint_schedule: '0: ("model1.ckpt"), 100: ("model2.safetensors")',
  enable_clipskip_scheduling: false,
  clipskip_schedule: '0: (2)',
  enable_noise_multiplier_scheduling: false,
  noise_multiplier_schedule: '0: (1.0)',
  resume_from_timestring: false,
  resume_timestring: '',
  enable_ddim_eta_scheduling: false,
  ddim_eta_schedule: '0: (0)',
  enable_ancestral_eta_scheduling: false,
  ancestral_eta_schedule: '0: (1)',
  amount_schedule: '0: (0.1)',
  kernel_schedule: '0: (5)',
  sigma_schedule: '0: (1)',
  threshold_schedule: '0: (0)',
  color_coherence: 'Image',
  color_coherence_image_path: 'D:/Users/User/Sonar/VIdeoArt/outputs/deforum-merged-previews/_cara_scene_init_576x1024.png',
  color_coherence_video_every_N_frames: 1,
  color_force_grayscale: false,
  legacy_colormatch: true,
  diffusion_cadence: 1,
  optical_flow_cadence: 'None',
  cadence_flow_factor_schedule: '0: (1)',
  optical_flow_redo_generation: 'None',
  redo_flow_factor_schedule: '0: (1)',
  diffusion_redo: '0'
};

const response = await fetch('http://127.0.0.1:7860/deforum_api/batches', {
  method: 'POST',
  headers: { 'content-type': 'application/json' },
  body: JSON.stringify({ deforum_settings: [settings], options_overrides: {} })
});
if (!response.ok) throw new Error(`${response.status} ${await response.text()}`);
const result = await response.json();
writeFileSync(
  path.join(previewRoot, 'CARA_DEFORUM_GETUP_V137_submit.json'),
  JSON.stringify({ submittedAt: new Date().toISOString(), result, settings }, null, 2)
);
console.log(JSON.stringify(result, null, 2));

